CONFIG_LOG=y
CONFIG_LOG_MODE_DEFERRED=y
CONFIG_STDOUT_CONSOLE=y
CONFIG_UART_CONSOLE=y

CONFIG_CAN=y
CONFIG_CAN_DEFAULT_BITRATE=500000
CONFIG_GPIO=y

#remove wonky characters from  zephyr logging output 
CONFIG_LOG_BACKEND_UART=y
CONFIG_LOG_BACKEND_SHOW_COLOR=n
CONFIG_LOG_PRINTK=y
CONFIG_LOG=y

#increase logger buffer/queue
CONFIG_LOG_BUFFER_SIZE=8192
CONFIG_LOG_PROCESS_THREAD_STACK_SIZE=2048