%% Equivalence Check / Playback Tool
% Reads 'simulation_data.csv' generated by the C++ simulation and plays
% it back using the MATLAB Animation and Plotter classes.

clear; clc; close all;
Parameters

% 2. Instantiate Visualization Classes
animation = Animation(Param);
plotter   = Plotter(Param);

% 3. Load C++ CSV Data
filename = 'simulation_data.csv';
%filename = 'matlab_data.csv'; % For testing MATLAB output
if ~isfile(filename)
    error('Could not find %s. Make sure you ran the C++ simulation and the file is in the current directory.', filename);
end

opts = detectImportOptions(filename);
opts.VariableNamingRule = 'preserve';
data_table = readtable(filename, opts);
data = table2array(data_table);

% 4. Parse CSV Columns
% 1      : t
% 2-18   : states (Truth) [17]
% 19-35  : estimate       [17]
% 36-45  : reference      [10]
% 46-52  : inputs (tau)   [7]
% 53-81  : measurements   [29]  <-- NEW
% 82-88  : model states   [7]   <-- NEW
% 89     : mode           [1]   <-- Shifted

time_log   = data(:, 1);
states_log = data(:, 2:18)';
est_log    = data(:, 19:35)';
ref_log    = data(:, 36:45)';
input_log  = data(:, 46:52)';
meas_log   = data(:, 53:81)'; % New
model_log  = data(:, 82:88)'; % New
mode_log   = data(:, 89)';    % New index

% 5. Map C++ Integer Modes to MATLAB String Modes
% Param.hpp: enum class PointingMode { OFF=0, DETUMBLE=1, POINT=2 };
mode_map = containers.Map({0, 1, 2}, {'off', 'detumble', 'point'});

% 6. Playback Loop
figure(Param.active_figure);

% Speed up playback if desired (1 = real time, 10 = 10x speed)
playback_speed = Inf; 
t_start_wall = tic;

fprintf('Starting Playback of %d data points...\n', length(time_log));

for k = 1:length(time_log)
    t = time_log(k);
    
    % --- Sync Playback to Real Time ---
    
    % --- Extract Vectors for this Time Step ---
    states_k = states_log(:, k);
    est_k    = est_log(:, k);
    ref_k    = ref_log(:, k);
    input_k  = input_log(:, k);
    
    % Convert Mode Int -> String
    mode_int = mode_log(k);
    if isKey(mode_map, mode_int)
        mode_str = mode_map(mode_int);
    else
        mode_str = 'off'; % Default
    end
    
    
    % Inside the loop:
    measurements_k = meas_log(:, k); % Now actually populated
    model_k        = model_log(:, k); % Now actually populated  
    % --- Update Visuals ---
    % 1. Animation
    animation.update(states_k, ref_k, mode_str);
    states_k(7:10) = states_k(7:10)*-1; % flip quaternion, it's still the same orientation though!
    % 2. Plotter
    % Signature: update(t, states, estimate, references, model, input, measurements, mode)
    plotter.update(t, states_k, est_k, ref_k, model_k, input_k, measurements_k, mode_str);
    
    % Force draw every N frames to keep UI responsive
end

fprintf('Playback Complete.\n');