# ===== Console & logging =====
CONFIG_LOG=y
CONFIG_LOG_MODE_DEFERRED=y
CONFIG_STDOUT_CONSOLE=y
CONFIG_UART_CONSOLE=y


# ===== Core kernel & power =====
CONFIG_TICKLESS_KERNEL=y
CONFIG_PM=y
CONFIG_PM_DEVICE=y
CONFIG_PM_DEVICE_RUNTIME=y


# ===== Drivers =====
CONFIG_GPIO=y
CONFIG_CAN=y
CONFIG_CAN_DEFAULT_BITRATE=500000
CONFIG_SENSOR=y # for internal sensors later
CONFIG_WATCHDOG=y # plan to feed IWDG


# ===== C++ =====
CONFIG_CPP=y
CONFIG_NEWLIB_LIBC=y
CONFIG_GLIBCXX_LIBCPP=y
# Keep these off unless needed:
# CONFIG_CPP_EXCEPTIONS=y
# CONFIG_RTTI=y


# ===== Settings / NVS (store IDs/config) =====
CONFIG_SETTINGS=y
CONFIG_SETTINGS_NVS=y
CONFIG_FLASH=y
CONFIG_NVS=y