CONFIG_RTC=y
CONFIG_RTC_STM32=y


# --- FLASH ---
CONFIG_FLASH=y
CONFIG_FLASH_MAP=y
CONFIG_MPU_ALLOW_FLASH_WRITE=y

# --- DMA / CACHE ---
CONFIG_DMA=n
CONFIG_SPI_STM32_DMA=n
CONFIG_CACHE_MANAGEMENT=y

# --- PERIPHERALS ---
CONFIG_GPIO=y
CONFIG_CAN=n
CONFIG_SPI=y
CONFIG_SPI_STM32=y
CONFIG_CAN_STM32_FDCAN=n

# --- CONSOLE (UART) ---
CONFIG_CONSOLE=y
CONFIG_STDOUT_CONSOLE=y
CONFIG_UART_CONSOLE=y
CONFIG_SERIAL=y

# --- RTT (disabled) ---
CONFIG_USE_SEGGER_RTT=n
CONFIG_RTT_CONSOLE=n

# --- PRINTK / LOGGING ---
CONFIG_PRINTK=y
CONFIG_LOG=y
CONFIG_LOG_BACKEND_RTT=n
CONFIG_LOG_BACKEND_UART=y
CONFIG_LOG_MODE_IMMEDIATE=y

# --- SEMIHOSTING (disabled) ---
CONFIG_SEMIHOST=n
CONFIG_SEMIHOST_CONSOLE=n

# --- POWER MANAGEMENT (disabled) ---
CONFIG_PM=n
CONFIG_PM_DEVICE=n
CONFIG_PM_DEVICE_RUNTIME=n
CONFIG_TICKLESS_KERNEL=n
